[package]
name = "dusk-bls12_381-sign"
version = "0.1.0"
authors = ["Jules de Smit <julesdesmit@gmail.com>"]
edition = "2018"

[dependencies]
canonical = { version = "0.5", optional = true }
canonical_derive = {version = "0.5", optional = true}
dusk-bls12_381 = { version = "0.6", default-features = false }
dusk-bytes = "0.1"
rand = "0.7"
rand_core = "0.5"
blake2 = "0.9"
thiserror = "1.0"
libc = "0.2"

[lib]
crate-type = ["rlib"]

[profile.release]
panic = 'abort'
lto = true
incremental = false
codegen-units = 1

[features]
default = ["std", "rand_core/getrandom"]
std = [
    "dusk-bls12_381/default",
    "canon",
]
canon = [
    "canonical",
    "canonical_derive",
    "dusk-bls12_381/canon",
    "dusk-bls12_381/groups",
]
